
	FROM openjdk
#create a workign directory inside the image
WORKDIR usr/lib
#setting environment variable same name as in applciation properties
ENV MONGO_DATABASE=productdb
ENV MONGO_URL=mongodb://localhost:27017/productdb

#copy executable jar file to the working directory
ADD ./target/  -0.0.1.SNAPSHOT.jar   usr/lib/product
#run the jar file
ENTRYPOINT["java","-jar","file name-SNAPSHOT "]




https://myrepos.stackroute.niit.com/678119_Aman/bej_c2_s4_rest_api_mongodb_pc_4.1/-/tree/master/product
