version: '3.3'
services:
  productservice:
    image: prodcutimage
    container_name: productcontainer
    build: userproductservice/
    restart: always
    network_mode: host
    ports:
      - 8090:8090
    depends_on:
      - mongoservice
      - eurekaserver

  mongoservice:
    image: mongo:3.2-jessie
    container_name: mongocontainer1
    ports:
      - 27017:27017
    network_mode: host

  userauthenticationservice:
    container_name: userauthenticationcontainer
    image: authenticationimage
    network_mode: host
    build: userauthenticationservice/
    restart: always
    ports:
      - 8085:8085
    depends_on:
      - mysqlservice
      - eurekaserver

  mysqlservice:
    image: mysql:5.5
    ports:
      - 3306:3306
    container_name: mysql-container
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  apigatewayservice:
    image: apigatewayimage
    container_name: apigatewaycontainer
    network_mode: host
    build: apigateway/
    restart: always
    depends_on:
      - eurekaserver
    ports:
      - 9000:9000

  eurekaserver:
    image: eureka-image
    build: eureka/
    restart: always
    network_mode: host
    ports:
      - 8761:8761