version: '3.3'
services:
  productservice:
    image: product_image
    container_name: productcontainers
    build: ./
    restart: always
    network_mode: host
    ports:
      - 8090:8090
    depends_on:
      - mongo
#this mango name is used in depends because productservice is dependent on mongo container
  mongo:
    image: mongo:3.2-jessie
    container_name: mongocontainer1
    ports:
      - 27017:27017
    network_mode: host
